name: loyaltyapp
description: PG Bison Loyalty App


publish_to: 'none'

version: 2.0.2+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  http: ^0.13.3
  url_launcher: ^6.0.6

  geolocator: ^7.0.3
  dio: ^4.0.0
  bloc: ^7.0.0
  rxdart: ^0.27.1
  font_awesome_flutter: ^8.8.1
  eva_icons_flutter: ^2.0.1
  flutter_bloc: ^7.0.1
  formz: ^0.4.0
  equatable: ^2.0.2
  uuid: ^3.0.4
  #multiselect_formfield: ^0.1.4
  multiselect_formfield: 0.1.6
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  meta: ^1.3.0
  country_code_picker: ^2.0.1
  fluttertoast: ^8.0.7
  pie_chart: ^5.0.0
  flutter_html: ^2.0.0
  google_fonts: ^2.1.0
  hexcolor: ^2.0.5
  group_radio_button: ^1.0.1
  customtogglebuttons: ^0.0.5
  bottom_bar_with_sheet: ^1.1.1
  mask_text_input_formatter: ^2.0.0
  flutter_widget_from_html: ^0.6.1
  flutter_swiper: ^1.1.6
  flutter_linkify: ^5.0.2
  intl_phone_number_input: ^0.7.0+2
  image_picker: ^0.8.4+4
  #image_picker: ^0.8.4+2
  #flutter_local_notifications:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"
  syncfusion_flutter_gauges: "18.4.49"
  syncfusion_flutter_charts: "18.4.49"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/pgbisonlogo.jpg"


flutter:


  uses-material-design: true


  assets:
    - res/images/drawer_header_background.png
    - assets/logo.png
    - assets/images/login.png
    - assets/pgbisonlogo.jpg
    - assets/PG_Bison_Green_Image.png
    - assets/pgbison_green_image.png


  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf

    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf

    - family: Poppins-Thin
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.otf

    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.otf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/poppins/Poppins-Medium.otf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.otf

    - family: Poppins-ExtraBold
      fonts:
        - asset: assets/fonts/poppins/Poppins-ExtraBold.otf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico/Pacifico.ttf

    - family: Poppins-ExtraLight
      fonts:
        - asset: assets/fonts/poppins/Poppins-ExtraLight.otf
